//
//  MapIconCatalog.swift
//  TimeJourney
//
//  Created by Codex on 2026/02/05.
//

import Foundation

enum MapIconCatalog {
    static let all: [String] = [
        "aerial_tramway_aerial_tramway_3d",
        "airplane_airplane_3d",
        "airplane_arrival_airplane_arrival_3d",
        "airplane_departure_airplane_departure_3d",
        "ambulance_ambulance_3d",
        "atm_sign_atm_sign_3d",
        "automobile_automobile_3d",
        "balloon_balloon_3d",
        "banana_banana_3d",
        "bank_bank_3d",
        "basketball_basketball_3d",
        "beer_mug_beer_mug_3d",
        "bicycle_bicycle_3d",
        "birthday_cake_birthday_cake_3d",
        "bone_bone_3d",
        "brain_brain_3d",
        "bread_bread_3d",
        "bullet_train_bullet_train_3d",
        "bus_bus_3d",
        "calendar_calendar_3d",
        "camera_camera_3d",
        "camping_camping_3d",
        "carousel_horse_carousel_horse_3d",
        "check_mark_check_mark_3d",
        "compass_compass_3d",
        "confetti_ball_confetti_ball_3d",
        "credit_card_credit_card_3d",
        "ferry_ferry_3d",
        "fire_fire_3d",
        "fishing_pole_fishing_pole_3d",
        "fork_and_knife_fork_and_knife_3d",
        "grapes_grapes_3d",
        "hamburger_hamburger_3d",
        "helicopter_helicopter_3d",
        "hospital_hospital_3d",
        "hotel_hotel_3d",
        "house_house_3d",
        "ice_cream_ice_cream_3d",
        "key_key_3d",
        "light_bulb_light_bulb_3d",
        "microscope_microscope_3d",
        "monorail_monorail_3d",
        "motorcycle_motorcycle_3d",
        "mountain_mountain_3d",
        "movie_camera_movie_camera_3d",
        "office_building_office_building_3d",
        "package_package_3d",
        "party_popper_party_popper_3d",
        "pill_pill_3d",
        "pizza_pizza_3d",
        "police_car_police_car_3d",
        "printer_printer_3d",
        "pushpin_pushpin_3d",
        "rocket_rocket_3d",
        "roller_coaster_roller_coaster_3d",
        "round_pushpin_round_pushpin_3d",
        "school_school_3d",
        "ship_ship_3d",
        "shopping_cart_shopping_cart_3d",
        "skateboard_skateboard_3d",
        "soccer_ball_soccer_ball_3d",
        "stadium_stadium_3d",
        "star_star_3d",
        "stethoscope_stethoscope_3d",
        "stop_sign_stop_sign_3d",
        "syringe_syringe_3d",
        "taxi_taxi_3d",
        "tennis_tennis_3d",
        "train_train_3d",
        "tram_car_tram_car_3d",
        "warning_warning_3d",
        "wine_glass_wine_glass_3d"
    ]
}
